"""empty message

Revision ID: d0da087aa543
Revises: c4140403182b
Create Date: 2020-06-10 22:54:20.238357

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0da087aa543'
down_revision = 'c4140403182b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cargos',
    sa.Column('id_cargo', sa.Integer(), nullable=False),
    sa.Column('id_empresa', sa.Integer(), nullable=True),
    sa.Column('nome_cargo', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['id_empresa'], ['empresa.id_empresa'], ),
    sa.PrimaryKeyConstraint('id_cargo')
    )
    op.create_table('usersApk',
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('id_cargo', sa.Integer(), nullable=True),
    sa.Column('id_empresa', sa.Integer(), nullable=True),
    sa.Column('nome_cliente', sa.Text(), nullable=False),
    sa.Column('cpf', sa.Text(), nullable=False),
    sa.Column('cidade', sa.Text(), nullable=False),
    sa.Column('estado', sa.Text(), nullable=False),
    sa.Column('pais', sa.Text(), nullable=False),
    sa.Column('numero', sa.Text(), nullable=False),
    sa.Column('data_nascimento', sa.Text(), nullable=False),
    sa.Column('celular', sa.Text(), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('instagram', sa.Text(), nullable=False),
    sa.Column('facebook', sa.Text(), nullable=False),
    sa.Column('whatsapp', sa.Text(), nullable=False),
    sa.Column('senha', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['id_cargo'], ['cargos.id_cargo'], ),
    sa.ForeignKeyConstraint(['id_empresa'], ['empresa.id_empresa'], ),
    sa.PrimaryKeyConstraint('id_usuario')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usersApk')
    op.drop_table('cargos')
    # ### end Alembic commands ###
